version: "3.8"

services:
  dev:
    container_name: dev
    restart: unless-stopped
    build:
      context: .
      target: dev
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules

  mysql:
    container_name: mysql
    image: mysql:8.3
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
